//
// Copyright (c) 2010 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT dnsproxy TEF3.0 tests
PRINT Run test case(s) for suite ns-dnsproxy-main
LOAD_SUITE	t_dnsproxy   -SharedData

RUN_UTILS  MkDir c:\private
RUN_UTILS  MkDir c:\private\101f7989
RUN_UTILS  MkDir c:\private\101f7989\esock
RUN_UTILS  MakeReadWrite c:\private\101f7989\esock\tcpip.ini
RUN_UTILS CopyFile c:\private\101f7989\esock\tcpip.ini c:\private\101f7989\esock\tcpip_old.ini
RUN_UTILS CopyFile z:\testdata\configs\tcpip_4dnxproxy.ini c:\private\101f7989\esock\tcpip.ini
RUN_UTILS DeleteFile  c:\private\200215F1\resolver.ini

// Configure CommDB for the tests
run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script

RUN_UTILS  MkDir c:\private
RUN_UTILS  MkDir c:\private\10202be9
RUN_UTILS  MkDir c:\private\10202be9\persists
RUN_UTILS  MakeReadWrite c:\private\10202be9\persists\cccccc00.cre

//ced -i z:\testdata\configs\testdnsproxy.xml
RUN_UTILS CopyFile z:\testdata\configs\cccccc00_dnsproxy1.cre c:\private\10202be9\persists\cccccc00.cre
run_script z:\TestData\scripts\te_esock_test_loadesock.script

START_TESTCASE NET-DNSProxy-globalUrl-001
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  New
	        COMMAND     	MainTestSection  TestGlobal ParamSection_globalUrl-001
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-globalUrl-001

START_TESTCASE NET-DNSProxy-globalUrl-002
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  New
	        COMMAND     	MainTestSection  TestGlobal ParamSection_globalUrl-002
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-globalUrl-002

START_TESTCASE NET-DNSProxy-globalUrl-003
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  New
	        COMMAND     	MainTestSection  TestGlobal ParamSection_globalUrl-003
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-globalUrl-003

START_TESTCASE NET-DNSProxy-localUrl-001
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  New
	        COMMAND     	MainTestSection  TestLocal ParamSection_localUrl-001
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-localUrl-001

START_TESTCASE NET-DNSProxy-localUrl-002
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  New
	        COMMAND     	MainTestSection  TestLocal ParamSection_localUrl-002
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-localUrl-002

RUN_UTILS MkDir  c:\private\200215F1\

RUN_UTILS CopyFile z:\testdata\configs\resolver01.ini c:\private\200215F1\resolver.ini
START_TESTCASE NET-DNSProxy-localUrl-002
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  New
	        COMMAND     	MainTestSection  TestLocal ParamSection_localUrl-002-Fail
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-localUrl-002

RUN_UTILS MakeReadWrite c:\private\200215F1\resolver.ini
RUN_UTILS CopyFile z:\testdata\configs\resolver02.ini c:\private\200215F1\resolver.ini
START_TESTCASE NET-DNSProxy-localUrl-002
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  New
	        COMMAND     	MainTestSection  TestLocal ParamSection_localUrl-002-Fail
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-localUrl-002

 
RUN_UTILS MakeReadWrite c:\private\200215F1\resolver.ini
RUN_UTILS DeleteFile  c:\private\200215F1\resolver.ini
START_TESTCASE NET-DNSProxy-localUrl-003
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  New
	        COMMAND     	MainTestSection  TestLocal ParamSection_localUrl-003
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-localUrl-003

START_TESTCASE NET-DNSProxy-localUrl-004
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  New
	        COMMAND     	MainTestSection  TestLocal ParamSection_localUrl-004
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-localUrl-004
START_TESTCASE NET-DNSProxy-Connection-001
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
  	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
  	        COMMAND     	MainTestSection  TestConnection ParamSection_conn-001
  	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-Connection-001
//ced -i z:\testdata\configs\testdnsproxy2.xml
RUN_UTILS CopyFile z:\testdata\configs\cccccc00_dnsproxy2.cre c:\private\10202be9\persists\cccccc00.cre
START_TESTCASE NET-DNSProxy-Connection-002
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
  	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
  	        COMMAND     	MainTestSection  TestConnection ParamSection_conn-002
  	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-Connection-002
//ced -i z:\testdata\configs\testdnsproxy3.xml
RUN_UTILS CopyFile z:\testdata\configs\cccccc00_dnsproxy3.cre c:\private\10202be9\persists\cccccc00.cre
START_TESTCASE NET-DNSProxy-Connection-003
	START_TEST_BLOCK    300     t_dnsproxy     z:\testdata\configs\ns-dnsproxy-maintest-ops_wlan.ini
	        CREATE_OBJECT   DnsProxyMainTestWrapper  MainTestSection
	        COMMAND     	MainTestSection  TestConnection ParamSection_conn-003
	END_TEST_BLOCK	
END_TESTCASE NET-DNSProxy-Connection-003

run_script z:\TestData\scripts\te_esock_test_unloadesockForced.script

RUN_UTILS MakeReadWrite c:\private\101f7989\esock\tcpip.ini
RUN_UTILS MakeReadWrite c:\private\101f7989\esock\tcpip_old.ini
RUN_UTILS DeleteFile c:\private\101f7989\esock\tcpip.ini
RUN_UTILS CopyFile c:\private\101f7989\esock\tcpip_old.ini c:\private\101f7989\esock\tcpip.ini
RUN_UTILS DeleteFile c:\private\101f7989\esock\tcpip_old.ini



//PRINT Completed_tef3_t_dnsproxy	
