// Copyright (c) 1997-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

/**
 @file
 @internalComponent 
*/

#if !defined(__PPP_VER_H__)
#define __PPP_VER_H__

#include <e32def.h>

const TUint KPPPMajorVersionNumber=1;
const TUint KPPPMinorVersionNumber=0;
const TUint KPPPBuildVersionNumber=18;

#endif  // _PPP_VER_H_
