//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Run all the unit test for the DND component

ced  z:\testdata\configs\te_unittestdnd.xml

RUN_UTILS DeleteFile c:\private\10000882\resolver.ini
RUN_UTILS CopyFile z:\testdata\configs\resolver_test1.ini c:\private\10000882\resolver.ini

PRINT TE_DND: Domain Name Daemon test

LOAD_SUITE te_dndServer -SharedData
START_TESTCASE          NET-DND-001
RUN_TEST_STEP  te_dndServer TestStepDND_Init 
END_TESTCASE            NET-DND-001


RUN_UTILS DeleteFile c:\private\10000882\resolver.ini
RUN_UTILS CopyFile z:\testdata\configs\resolver_test2.ini c:\private\10000882\resolver.ini

START_TESTCASE          NET-DND-002
RUN_TEST_STEP  	te_dndServer TestStepDND_Init 
END_TESTCASE            NET-DND-002

PRINT configuring epoc in ipv6 network mode

ced  z:\testdata\configs\te_ipv6config.cfg

START_TESTCASE          NET-DND-003
RUN_TEST_STEP  	te_dndServer TestStepDND_Init 
END_TESTCASE            NET-DND-003


PRINT Completed the unit testing for the DND component