//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//*************************************************************************************
//*
//* 	Run TE_LLMNR test for Ipv6
//*
//*************************************************************************************


//-- create commsDB for Ipv6
ced -i z:\TestData\configs\LLMNR\te_llmnr_ip6.xml ced.log

//-- run generic test script
run_script z:\TestData\scripts\LLMNR\te_llmnr.script


