// Copyright (c) 2004-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//



/**
 @internalComponent
*/
#if !defined(__LOG_IPSECPOL_H__)
#define __LOG_IPSECPOL_H__

#include <comms-infras/commsdebugutility.h>

__FLOG_STMT(_LIT8(KLogComponent, "ipspol");) // subsystem name

#include "logcommon.h"

#endif // __LOG_IPSECPOL_H__
