/**
* Copyright (c) 1997-2009 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:
*
*/



/**
 @file SLIP_VER.H
 @internalComponent
*/

#if !defined(__SLIP_VER_H__)
#define __SLIP_VER_H__

const TUint KSlipMajorVersionNumber=1;  ///< Slip Major Version Number
const TUint KSlipMinorVersionNumber=0;  ///< Slip Minor Version Number
const TUint KSlipBuildVersionNumber=10; ///< Slip bUILD Version Number

#endif  // _SLIP_VER_H_
