//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Perform all the TS_QoSAPI tests
PRINT

run_script z:\TestData\scripts\esock_test_unloadesockForced.script
ced z:\testdata\configs\ts_qosapi.xml ced.log
run_script z:\TestData\scripts\esock_test_loadesock.script

//
// Implicit Sockets IP4 Udp
//
run_script z:\testdata\scripts\ImplicitUdp\QoS_Scenario_16_HLR5_5_2.script - Problem with Join

// Close all possible opened sessions
RUN_SCRIPT Z:\TestData\Scripts\esock_test_stopallinterfaces.script

run_script z:\TestData\scripts\esock_test_unloadesockForced.script

PRINT
PRINT TS_QoSAPI tests complete
