//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//Create the CommDb required for the NullAgent tests
RUN_SCRIPT z:\TestData\scripts\esock_test_unloadesockForced.script
ced z:\TestData\configs\nullagenttest.xml ced.log
RUN_SCRIPT z:\TestData\scripts\esock_test_loadesock.script
