//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

LOAD_SUITE TlsProvServer

// copy in the certstore needed for the cert validation tests

RUN_UTILS DeleteFile c:\private\101f72a6\CACerts.dat 
RUN_UTILS DeleteFile c:\private\101f72a6\certclients.dat
RUN_UTILS DeleteFile c:\private\101f72a6\keys.dat
RUN_UTILS CopyFile z:\testdata\configs\tlsprovtestdata\KeyAndCertStore\cacerts.dat c:\private\101f72a6\CACerts.dat
RUN_UTILS CopyFile z:\testdata\configs\tlsprovtestdata\KeyAndCertStore\certclients.dat    c:\private\101f72a6\certclients.dat 
RUN_UTILS CopyFile z:\testdata\configs\tlsprovtestdata\KeyAndCertStore\keys.dat    c:\private\101f72a6\keys.dat 

// run 3 different test steps

//! @SYMTestCaseID 	SEC-TLSP-WILDCARD-0001

START_TESTCASE SEC-TLSP-WILDCARD-0001
RUN_TEST_STEP 10 TlsProvServer ServerCertStep z:\testdata\scripts\te_tlsprov.ini altname_wildcard_rfc2595_pass
RUN_TEST_STEP 10 TlsProvServer ServerCertStep z:\testdata\scripts\te_tlsprov.ini altname_wildcard_pass
RUN_TEST_STEP 10 TlsProvServer ServerCertStep z:\testdata\scripts\te_tlsprov.ini altname_wildcard_fail
END_TESTCASE SEC-TLSP-WILDCARD-0001
