//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//
PRINT Run all Tls provider tests
//
LOAD_SUITE TlsProvServer
//
#

//! @SYMTestCaseID 	SEC-TLSP-CLIENT-AUTHDLG-0001
//! @SYMTestCaseDesc 	start a secure connection to the test server which needs client authentication
//!			(ClientAuthDlg)
//! @SYMREQ 		DEF074672 
//! @SYMTestPriority 	High
//! @SYMTestActions  	Test client authentication dialog
//! @SYMTestExpectedResults the client authentication successfully 
//! @SYMDevelopedForRelease Mike

START_TESTCASE SEC-TLSP-CLIENT-AUTHDLG-0001

RUN_UTILS DeleteFile c:\private\200008d1\101f52c4.cce

RUN_TEST_STEP 180 TlsProvServer TSecureConnection C:\ttlsprovider\tsecuretlsdialog\scripts\tsecuretlsdialog.ini SecureDialog_1

RUN_UTILS DeleteFile c:\private\200008d1\101f52c4.cce

RUN_TEST_STEP 180 TlsProvServer TSecureConnection C:\ttlsprovider\tsecuretlsdialog\scripts\tsecuretlsdialog.ini SecureDialog_2

RUN_UTILS DeleteFile c:\private\200008d1\101f52c4.cce

RUN_TEST_STEP 180 TlsProvServer TSecureConnection C:\ttlsprovider\tsecuretlsdialog\scripts\tsecuretlsdialog.ini SecureDialog_3

RUN_UTILS DeleteFile c:\private\200008d1\101f52c4.cce

RUN_TEST_STEP 180 TlsProvServer TSecureConnection C:\ttlsprovider\tsecuretlsdialog\scripts\tsecuretlsdialog.ini SecureDialog_4

RUN_UTILS DeleteFile c:\t_secdlg_in.dat

RUN_UTILS DeleteFile c:\t_secdlg_out.dat

END_TESTCASE SEC-TLSP-CLIENT-AUTHDLG-0001
