// Copyright (c) 2003-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
 
// Makmake-generated uid source file
#include <E32STD.H>
#pragma data_seg(".E32_UID")
__WINS_UID(0x10000079,0x10003d3a,0x1000022c)
#pragma data_seg()
