// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Contains integration tests for UPS server.
// 
//

PRINT Run Basic integration test cases for PREQ1116 ( IP Networking User Prompting )

RUN_PROGRAM -1 SETCAP te_ipups.exe 0003FFFE -SID A0000001 te_ipups_un_prot_sid.exe
RUN_PROGRAM -1 SETCAP te_ipups.exe 0003FFFE -SID 10000001 te_ipups_1.exe
RUN_PROGRAM -1 SETCAP te_ipups.exe 0003FFFE -SID 10000002 te_ipups_2.exe

LOAD_SUITE te_ipups
LOAD_SUITE te_ipups_1
LOAD_SUITE te_ipups_2
LOAD_SUITE te_ipups_un_prot_sid


START_TESTCASE ProtSidPlatSecFail
//!@SYMTestCaseID NET-IP-UPS-1001
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Prompt when protected SID, platsec fails.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini ProtSidPlatSecFail
END_TESTCASE ProtSidPlatSecFail

START_TESTCASE UnProtSidPlatSecPass
//!@SYMTestCaseID NET-IP-UPS-1002
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Prompt when unprotected SID, platsec passes.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups_un_prot_sid IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini UnProtSidPlatSecPass
END_TESTCASE UnProtSidPlatSecPass

START_TESTCASE UnProtSidPlatSecFail
//!@SYMTestCaseID NET-IP-UPS-1003
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Prompt when unprotected SID, platsec fails.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups_un_prot_sid IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini UnProtSidPlatSecFail
END_TESTCASE UnProtSidPlatSecFail

START_TESTCASE ProtSidPlatSecPass
//!@SYMTestCaseID NET-IP-UPS-1004
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc No Prompt when protected SID, platsec passes.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini ProtSidPlatSecPass
END_TESTCASE ProtSidPlatSecPass

START_TESTCASE ValidPromptResponse
//!@SYMTestCaseID NET-IP-UPS-1005
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Prompt only offers SessionYes, SessionNo, Always & Never.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini ValidPromptResponse
END_TESTCASE ValidPromptResponse

START_TESTCASE ValidDestinationIPPrompted
//!@SYMTestCaseID NET-IP-UPS-1006
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Prompt contains details of client.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini ValidDestinationIPPrompted
END_TESTCASE ValidDestinationIPPrompted

START_TESTCASE UserResponseSessionYes
//!@SYMTestCaseID NET-IP-UPS-1007
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Client receives correct SessionYes response.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini UserResponseSessionYes
END_TESTCASE UserResponseSessionYes

START_TESTCASE PromptAgainAfterSessionYes
//!@SYMTestCaseID NET-IP-UPS-1008
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Prompt again after response first SessionYes response.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini PromptAgainAfterSessionYes
END_TESTCASE PromptAgainAfterSessionYes

START_TESTCASE PromptAfterSessionYesWithNewSubSession
//!@SYMTestCaseID NET-IP-UPS-1009
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Prompt when starting subsequent sub session after initial SessionYes.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini PromptAfterSessionYesWithNewSubSession
END_TESTCASE PromptAfterSessionYesWithNewSubSession

START_TESTCASE PromptAgainAfterSessionNo
//!@SYMTestCaseID NET-IP-UPS-1010
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Prompt again after response SessionNo.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini PromptAgainAfterSessionNo
END_TESTCASE PromptAgainAfterSessionNo

START_TESTCASE PromptAfterSessionNoWithNewSubSession
//!@SYMTestCaseID NET-IP-UPS-1011
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Prompt when starting subsequent sub session after initial SessionNo.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini PromptAfterSessionNoWithNewSubSession
END_TESTCASE PromptAfterSessionNoWithNewSubSession

START_TESTCASE NoPromptAfterAlwaysResponse
//!@SYMTestCaseID NET-IP-UPS-1012
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User response Always - No further Prompting in same session.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini NoPromptAfterAlwaysResponse
END_TESTCASE NoPromptAfterAlwaysResponse

START_TESTCASE NoPromptInNewSessionAfterAlways
//!@SYMTestCaseID NET-IP-UPS-1013
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User response Always - No further Prompting in subsequent session.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini NoPromptInNewSessionAfterAlways
END_TESTCASE NoPromptInNewSessionAfterAlways

START_TESTCASE NoPromptInSameSessionAfterNever
//!@SYMTestCaseID NET-IP-UPS-1014
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User response Never - No further Prompting in same session.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini NoPromptInSameSessionAfterNever
END_TESTCASE NoPromptInSameSessionAfterNever

START_TESTCASE NoPromptInNewSessionAfterNever
//!@SYMTestCaseID NET-IP-UPS-1015
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User response Never - No further Prompting in subsequent session.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini NoPromptInNewSessionAfterNever
END_TESTCASE NoPromptInNewSessionAfterNever

START_TESTCASE UserResponseYes
//!@SYMTestCaseID NET-IP-UPS-1016
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User returned response SessionYes and receives same.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini UserResponseYes
END_TESTCASE UserResponseYes

START_TESTCASE UserResponseNo
//!@SYMTestCaseID NET-IP-UPS-1017
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc User returned response SessionNo and receives same.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini UserResponseNo
END_TESTCASE UserResponseNo

START_TESTCASE MultipleClientWithSessionYesAndSessionNo
//!@SYMTestCaseID NET-IP-UPS-1018
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Multiple UPS SubSessions and clients - SessionYes + SessionNo User response.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsNotifyCount z:\testdata\configs\te_ipups\te_ipups.ini StorePromptTriggerCount
CONCURRENT
RUN_TEST_STEP 100 te_ipups_1 IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client1UserResponseSessionYes
DELAY 1
RUN_TEST_STEP 100 te_ipups_2 IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client2UserResponseSessionNo
DELAY 1
RUN_TEST_STEP 100 te_ipups   IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client2UserResponseSessionNo
CONSECUTIVE
RUN_TEST_STEP 100 te_ipups IpUpsNotifyCount z:\testdata\configs\te_ipups\te_ipups.ini PromptCount_3
END_TESTCASE MultipleClientWithSessionYesAndSessionNo

START_TESTCASE MultipleClientWithAlwaysAndNever
//!@SYMTestCaseID NET-IP-UPS-1019
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Multiple UPS SubSessions and Clients - Always + Never User responses.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsNotifyCount z:\testdata\configs\te_ipups\te_ipups.ini StorePromptTriggerCount
CONCURRENT
RUN_TEST_STEP 100 te_ipups_1 IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client1UserResponseAlways
DELAY 1
RUN_TEST_STEP 100 te_ipups_2 IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client2UserResponseNever
DELAY 1
RUN_TEST_STEP 100 te_ipups   IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client2UserResponseNever
CONSECUTIVE
RUN_TEST_STEP 100 te_ipups IpUpsNotifyCount z:\testdata\configs\te_ipups\te_ipups.ini PromptCount_3
END_TESTCASE MultipleClientWithAlwaysAndNever

START_TESTCASE MultipleClientWithAlwaysAndSessionNo
//!@SYMTestCaseID NET-IP-UPS-1020
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Multiple UPS SubSessions and clients - Always + SessionNo User Responses.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsNotifyCount z:\testdata\configs\te_ipups\te_ipups.ini StorePromptTriggerCount
CONCURRENT
RUN_TEST_STEP 100 te_ipups_1 IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client1UserResponseAlways
DELAY 1
RUN_TEST_STEP 100 te_ipups_2 IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client2UserResponseSessionNo
DELAY 1
RUN_TEST_STEP 100 te_ipups   IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client2UserResponseSessionNo
CONSECUTIVE
RUN_TEST_STEP 100 te_ipups IpUpsNotifyCount z:\testdata\configs\te_ipups\te_ipups.ini PromptCount_3
END_TESTCASE MultipleClientWithAlwaysAndSessionNo

START_TESTCASE MultipleClientWithSessionYesAndNever
//!@SYMTestCaseID NET-IP-UPS-1021
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Multiple UPS SubSessions and clients - SessionYes + Never User Responses.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsNotifyCount z:\testdata\configs\te_ipups\te_ipups.ini StorePromptTriggerCount
CONCURRENT
RUN_TEST_STEP 100 te_ipups_1 IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client1UserResponseSessionYes
DELAY 1
RUN_TEST_STEP 100 te_ipups_2 IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client2UserResponseNever
DELAY 1
RUN_TEST_STEP 100 te_ipups 	 IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini Client2UserResponseNever
CONSECUTIVE
RUN_TEST_STEP 100 te_ipups IpUpsNotifyCount z:\testdata\configs\te_ipups\te_ipups.ini PromptCount_3
END_TESTCASE MultipleClientWithSessionYesAndNever

START_TESTCASE MultipleSubSessionsWithAlways
//!@SYMTestCaseID NET-IP-UPS-1022
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Multiple UPS SubSessions, single client - Always + No prompt.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini MultipleSubSessionsWithAlways
END_TESTCASE MultipleSubSessionsWithAlways

START_TESTCASE MultipleSubSessionsWithSessionYes
//!@SYMTestCaseID NET-IP-UPS-1023
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Multiple UPS SubSessions, single client - SessionYes + Prompt.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini MultipleSubSessionsWithSessionYes
END_TESTCASE MultipleSubSessionsWithSessionYes

START_TESTCASE CancelPromptCall
//!@SYMTestCaseID NET-IP-UPS-1024
//!@SYMPREQ PREQ1116
//!@SYMTestCaseDesc Cancel authorisation request mid-prompting.
//!@SYMTestPriority Critical
//!@SYMTestActions Start UPS Session, SubSession and call Authorise.
//!@SYMTestExpectedResults Pass
//!@SYMTestType CIT

RUN_TEST_STEP 100 te_ipups IpUpsDeleteDecisionDB
RUN_TEST_STEP_RESULT  -3 100 te_ipups IpUpsStep z:\testdata\configs\te_ipups\te_ipups.ini CancelPromptCall
END_TESTCASE CancelPromptCall
